#server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ao_phong_4p;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#spring.web.resources.static-locations=classpath:/static/
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#thymeleaf.layout.prefix=classpath:/templates/
#thymeleaf.layout.suffix=.html
#thymeleaf.layout.enable=true
#thymeleaf.layout.dialect-prefix=layout

#cau hinh du an den thu muc webapp
spring.thymeleaf.prefix=/views/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.template-resolver-order=1

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
upload.directory=uploads/
# Cấu hình Spring Mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=linhtnph31789@fpt.edu.vn
#spring.mail.password=jole zsxx ycsd gkbg
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=linhtnph31789@fpt.edu.vn
spring.mail.password=jolezsxxycsdgkbg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#api dia chi checkout online
ghn.api.key=9ce1bd74-9fc8-11ef-819a-9e59fa82dda0
ghn.service=9ce1bd74-9fc8-11ef-819a-9e59fa82dda0
ghn.shopId=5448630

ghn.api.url=https://dev-online-gateway.ghn.vn/ship/public-api/v2/shipping-order/fee
#ghn.api.url=https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee

# Session timeout sau 15 phút (15m), có thể đổi sang 10m, 30m...
# Session config
# Session timeout 30 phút
server.servlet.session.timeout=30m
server.servlet.session.cookie.max-age=1800
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax

# Debug session
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG


#Cau hinh cloudinary ?? luu anh, ? lien ket tk : tienbbph31709@fpt.edu.vn
cloudinary.cloud_name=dtasowmgo
cloudinary.api_key=281173734364872
cloudinary.api_secret=AAL-hG2H27G2uJ1y4bDpMbX9zLk

#TienBB : Cau hinh thanh toan momo
#account đăng nhập app: 01665142537
#passs  : full số 0
# otp cũng là full số 0, mã này tự nhập, sẽ không gửi về máy
momo.offline.env=sandbox
momo.offline.partnerCode=MOMOZVVD20250910_TEST
momo.offline.accessKey=aclpamTX9aNFl6Fa
momo.offline.secretKey=9dIppQPvXq6sVGgGIP9AqTasgl0bJymp
momo.offline.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.offline.returnUrl=http://localhost:8080/admin/sell-inline/momo-return
momo.offline.notifyUrl=http://localhost:8080/admin/sell-inline/momo-ipn


momo.online.env=sandbox
momo.online.partnerCode=MOMOZVVD20250910_TEST
momo.online.accessKey=aclpamTX9aNFl6Fa
momo.online.secretKey=9dIppQPvXq6sVGgGIP9AqTasgl0bJymp
momo.online.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.online.returnUrl=http://localhost:8080/thank-you
momo.online.notifyUrl=http://localhost:8080/momo-ipn
spring.jpa.open-in-view=true


